### ISSUE TITLE
Return actually assigned name in `JoinResponse`

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-grpc#12]

**Comment by Kiyotoko** [comment]
Why does the client needs the name?

**Comment by Belissimo-T** [comment]
@Kiyotoko You're right, the client should not know the identity (or name) of any other client. However, then, there should not be a `name` field of `Player` either. Currently, this name field just contains the requested name which, in the Python server, gets modified for when two clients request an identical name.  However, this behaviour is not documented and the Java server does not do that.

I like the idea of a render client (for which we would kind of need this attribute) but I think we're not ready for that yet. Let's remove the `Player.name` attribute for now.
https://github.com/seekers-dev/seekers-grpc/blob/e0ec52ea74bab4733c454b1f3d1461dfbc0df93a/src/main/proto/org/seekers/game/player.proto#L17-L18

**Comment by Kiyotoko** [comment]
I will fix this. I think it we should then consequently also remove `Player.color` attribute, because this also does only show the identity.

**Comment by Belissimo-T** [comment]
@Kiyotoko 
I can't believe we're agreeing on something hahaha. You're right, `Player.color` should be removed, too.

I don't quite get why you want to change the `JoinRequest`, though... Please elaborate.

**Comment by Kiyotoko** [comment]
This was added in the last pull request (#51 )
