### ISSUE TITLE
Combine `GameDescription.address` and `GameDescription.port`

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-grpc#3]
We only need the address, the following is equivalent:

### Old:
Address: `localhost`
Port: `5050`

### Proposed
Address: `localhost:5050`

There is no benefit in separating port and address (for the python client side at least). I don't know how Java handles ports.

**Comment by karl-zschiebsch** [comment]
Java seperates host and port, that's why I split it up.
